### ISSUE TITLE
negative values after deconvolusion

### ISSUE THREAD

**Issue by AhmedMohamed1993** [xanibas/granulator#1]
Hi, 

I tried to do the deconvolusion on bulk RNA data from sorted memory B cells. The values I get, go out of the expected range (attached): sometimes over 100 and sometimes with negative values. Do you have an idea what might cause this issue?
I have not used a dataset for benchmarking. 
Thank you.

![Granulator_Deconvolution](https://user-images.githubusercontent.com/74005107/182908476-14c16cfb-ca5f-40f8-93d7-384423b1199d.png)

**Comment by xanibas** [comment]
Please refer to the [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/granulator/inst/doc/granulator.html) instructions:
"Although there may be slightly negative proportions, significant negative values means that deconvolution methods fails to converge on a biological meaningful solution, and the reference profile matrix should be further refined."
