### ISSUE TITLE
help wanted 

### ISSUE THREAD

**Issue by SaraAlidadiani** [xanibas/granulator#2]
Hi, 

I used data of snRNAseq of the brain for my cell proportion. Now, I have my cell proportion .csv file, and I would like to use a granulator for deconvolution, but there is a problem in the following line of your code:

> decon <- deconvolute(m = bulkRNAseq_ABIS, sigMatrix = sigList)

For m I have to define my own bulk RNA data  (not the result of cell proportion)? 
And what I have to define for the sigMatrix ?

As I already used another method for cell proportion and I do not have a different kind of matrix that you used.

Looking forward to your kind explanation!

**Comment by xanibas** [comment]
Hi, yes that's correct, m is the data you want to deconvolute, sigMatrix is a list of reference profiles to perform the deconvolution. Granulator does not have methods that work on cell proportions directly. In the [vignette ](https://www.bioconductor.org/packages/release/bioc/vignettes/granulator/inst/doc/granulator.html)there is example data that explain the input of the function
